[package]
name = "aether-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
aether-core = { path = "../aether-core" }
aether-agent-api = { path = "../aether-agent-api" }
eframe.workspace = true
egui.workspace = true
egui_plot.workspace = true
egui_dock.workspace = true
crossbeam-channel.workspace = true
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
serde.workspace = true
rfd = { workspace = true }
probe-rs = { workspace = true }
syntect = "5.2"
tokio = { version = "1.0", features = ["sync", "rt", "net", "time", "macros"] }
